def raise_exception():
    pass